CREATE TABLE TBL_USUARIOS (
	CD_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DS_USUARIO VARCHAR(50) NOT NULL,
    DS_NOME VARCHAR(100) NOT NULL,
    DS_SOBRENOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO DATETIME NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL,
    DS_ENDERECO VARCHAR(100) NOT NULL,
    DS_BAIRRO VARCHAR (100) NOT NULL,
    DS_COMPLEMENTO VARCHAR(20) NOT NULL,
    DS_CIDADE VARCHAR(50) NOT NULL,
    DS_ESTADO VARCHAR(20) NOT NULL,
    NR_CEP VARCHAR(10) NOT NULL,
    X_TERMOS_DE_USO BIT NULL,
    X_LOGIN_SALVO BIT NULL
);